export default function thaiNumbersPhonetic(number: number) {
    switch (number) {
        case 0: return 'soon';
        case 1: return 'nùeng';
        case 2: return 'săwng';
        case 3: return 'săam';
        case 4: return 'sìi';
        case 5: return 'hâa';
        case 6: return 'hòk';
        case 7: return 'jèt';
        case 8: return 'bpàed';
        case 9: return 'gâao';
        case 10: return 'sìp';
        case 11: return 'sìp èt';
        case 12: return 'sìp săwng';
        case 13: return 'sìp săam';
        case 14: return 'sìp sìi';
        case 15: return 'sìp hâa';
        case 16: return 'sìp hòk';
        case 17: return 'sìp jèt';
        case 18: return 'sìp bpàed';
        case 19: return 'sìp gâao';
        case 20: return 'yîi sìp';
        case 21: return 'yîi sìp èt';
        case 22: return 'yîi sìp săwng';
        case 23: return 'yîi sìp săam';
        case 24: return 'yîi sìp sìi';
        case 25: return 'yîi sìp hâa';
        case 26: return 'yîi sìp hòk';
        case 27: return 'yîi sìp jèt';
        case 28: return 'yîi sìp bpàed';
        case 29: return 'yîi sìp gâao';
        case 30: return 'săam sìp';
        case 31: return 'săam sìp èt';
        case 32: return 'săam sìp săwng';
        case 33: return 'săam sìp săam';
        case 34: return 'săam sìp sìi';
        case 35: return 'săam sìp hâa';
        case 36: return 'săam sìp hòk';
        case 37: return 'săam sìp jèt';
        case 38: return 'săam sìp bpàed';
        case 39: return 'săam sìp gâao';
        case 40: return 'sìi sìp';
        case 41: return 'sìi sìp èt';
        case 42: return 'sìi sìp săwng';
        case 43: return 'sìi sìp săam';
        case 44: return 'sìi sìp sìi';
        case 45: return 'sìi sìp hâa';
        case 46: return 'sìi sìp hòk';
        case 47: return 'sìi sìp jèt';
        case 48: return 'sìi sìp bpàed';
        case 49: return 'sìi sìp gâao';
        case 50: return 'hâa sìp';
        case 51: return 'hâa sìp èt';
        case 52: return 'hâa sìp săwng';
        case 53: return 'hâa sìp săam';
        case 54: return 'hâa sìp sìi';
        case 55: return 'hâa sìp hâa';
        case 56: return 'hâa sìp hòk';
        case 57: return 'hâa sìp jèt';
        case 58: return 'hâa sìp bpàed';
        case 59: return 'hâa sìp gâao';
        default: return '';
    }
}